version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Eliot.2002
      POSTGRES_USER: eliot
      POSTGRES_DB: db-back-end
    ports:
      - "5432:5432"

  app:
    image: back-end
    ports:
      - "13000:3000"
